-- ============================================================
-- 01_schema_design.sql
-- Financial Transaction Monitoring & AML/KYC Compliance System
-- Database: MySQL 8.0+
-- ============================================================

-- Create database
CREATE DATABASE IF NOT EXISTS aml_monitoring;
USE aml_monitoring;

-- ============================================================
-- FACT TABLE: All financial transactions
-- ============================================================
CREATE TABLE IF NOT EXISTS fact_transactions (
    transaction_id          INT AUTO_INCREMENT PRIMARY KEY,
    step                    INT NOT NULL,                    -- 1 step = 1 hour of simulation
    transaction_type        VARCHAR(20) NOT NULL,            -- PAYMENT, TRANSFER, CASH_OUT, DEBIT, CASH_IN
    amount                  DECIMAL(15,2) NOT NULL,
    customer_id             VARCHAR(50) NOT NULL,            -- nameOrig (sender)
    old_balance_orig        DECIMAL(15,2),
    new_balance_orig        DECIMAL(15,2),
    recipient_id            VARCHAR(50) NOT NULL,            -- nameDest (receiver)
    old_balance_dest        DECIMAL(15,2),
    new_balance_dest        DECIMAL(15,2),
    is_fraud                TINYINT DEFAULT 0,               -- 0 = legitimate, 1 = fraudulent
    is_flagged_fraud        TINYINT DEFAULT 0,               -- 0 = not flagged, 1 = flagged by system
    -- Derived columns (populated during ETL)
    transaction_hour        INT,                             -- step % 24 (hour of day)
    transaction_day         INT,                             -- step / 24 (day number)
    balance_change          DECIMAL(15,2),                   -- new_balance_orig - old_balance_orig
    amount_to_balance_ratio DECIMAL(10,4)                    -- amount / old_balance_orig (NULL if old_balance = 0)
) ENGINE=InnoDB;

-- ============================================================
-- DIMENSION TABLE: Customer Profiles (aggregated from fact)
-- ============================================================
CREATE TABLE IF NOT EXISTS dim_customers (
    customer_id         VARCHAR(50) PRIMARY KEY,
    total_transactions  INT DEFAULT 0,
    total_amount        DECIMAL(15,2) DEFAULT 0.00,
    avg_transaction     DECIMAL(15,2) DEFAULT 0.00,
    max_transaction     DECIMAL(15,2) DEFAULT 0.00,
    fraud_count         INT DEFAULT 0,
    first_seen_step     INT,
    last_seen_step      INT,
    risk_tier           VARCHAR(20) DEFAULT 'LOW',           -- CRITICAL, HIGH, MEDIUM, LOW
    risk_score          INT DEFAULT 0                        -- 0-100 numeric score
) ENGINE=InnoDB;

-- ============================================================
-- DIMENSION TABLE: Transaction Types with risk weights
-- ============================================================
CREATE TABLE IF NOT EXISTS dim_transaction_types (
    type_id         INT AUTO_INCREMENT PRIMARY KEY,
    type_name       VARCHAR(20) UNIQUE NOT NULL,
    risk_weight     DECIMAL(3,2) DEFAULT 1.00,               -- multiplier for risk scoring
    description     VARCHAR(100)
) ENGINE=InnoDB;

-- Pre-populate transaction types with risk weights
INSERT INTO dim_transaction_types (type_name, risk_weight, description) VALUES
    ('CASH_IN',   0.20, 'Customer deposits cash into account'),
    ('CASH_OUT',  0.80, 'Customer withdraws cash from account'),
    ('DEBIT',     0.40, 'Direct debit/automatic payment'),
    ('PAYMENT',   0.30, 'Payment for goods or services'),
    ('TRANSFER',  0.90, 'Transfer to another account - highest fraud risk');

-- ============================================================
-- ALERTS TABLE: Generated by anomaly detection
-- ============================================================
CREATE TABLE IF NOT EXISTS alerts (
    alert_id            INT AUTO_INCREMENT PRIMARY KEY,
    transaction_id      INT,
    customer_id         VARCHAR(50),
    alert_type          VARCHAR(50) NOT NULL,                 -- HIGH_AMOUNT, VELOCITY, BALANCE_DRAIN, Z_SCORE, IQR
    severity            VARCHAR(10) NOT NULL,                 -- CRITICAL, HIGH, MEDIUM, LOW
    alert_description   VARCHAR(255),
    detection_method    VARCHAR(50),                          -- SQL, PYTHON_ZSCORE, PYTHON_IQR, PYTHON_ROLLING
    alert_timestamp     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    reviewed            TINYINT DEFAULT 0,                    -- 0 = pending, 1 = reviewed
    false_positive      TINYINT DEFAULT NULL,                 -- NULL = unreviewed, 0 = true alert, 1 = false positive
    reviewer_notes      TEXT,
    FOREIGN KEY (transaction_id) REFERENCES fact_transactions(transaction_id),
    INDEX idx_alert_severity (severity),
    INDEX idx_alert_type (alert_type),
    INDEX idx_alert_reviewed (reviewed)
) ENGINE=InnoDB;

-- ============================================================
-- REPORTING TABLE: Daily monitoring summaries
-- ============================================================
CREATE TABLE IF NOT EXISTS daily_monitoring_report (
    report_id           INT AUTO_INCREMENT PRIMARY KEY,
    report_day          INT NOT NULL,                         -- day number from simulation
    total_txns          INT,
    total_volume        DECIMAL(15,2),
    fraud_count         INT,
    fraud_rate          DECIMAL(8,4),                         -- percentage
    avg_txn_amount      DECIMAL(15,2),
    max_txn_amount      DECIMAL(15,2),
    alert_count         INT,
    high_risk_customers INT,
    report_generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_report_day (report_day)
) ENGINE=InnoDB;

-- ============================================================
-- INDEXES on fact_transactions for query performance
-- ============================================================
CREATE INDEX idx_ft_customer      ON fact_transactions(customer_id);
CREATE INDEX idx_ft_recipient     ON fact_transactions(recipient_id);
CREATE INDEX idx_ft_type          ON fact_transactions(transaction_type);
CREATE INDEX idx_ft_fraud         ON fact_transactions(is_fraud);
CREATE INDEX idx_ft_day           ON fact_transactions(transaction_day);
CREATE INDEX idx_ft_hour          ON fact_transactions(transaction_hour);
CREATE INDEX idx_ft_amount        ON fact_transactions(amount);
CREATE INDEX idx_ft_step          ON fact_transactions(step);

-- Composite indexes for common query patterns
CREATE INDEX idx_ft_type_fraud    ON fact_transactions(transaction_type, is_fraud);
CREATE INDEX idx_ft_cust_step     ON fact_transactions(customer_id, step);
CREATE INDEX idx_ft_day_type      ON fact_transactions(transaction_day, transaction_type);
